url: https://cciradih.top/
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
title: Cciradih
description: lim _ ( t -> oo ) i = c
author: Cciradih
logo: /assets/logo.png
social:
  name: Cciradih
  links:
    - https://github.com/cciradih/
    - https://shang.qq.com/wpa/qunwpa?idkey=18ce00de201537ad6cb4eb43577815ef44a5b8a03c6f2c6ab7a9ddfa789e3848
    - mailto:mountain@cciradih.top
lang: zh-Hans
paginate: 15
paginate_path: "page:num"
