url: https://cciradih.top
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
title: Limtooic
description: lim _ ( t -> oo ) i = c
author: Cciradih
logo: /assets/logo.png
social:
  name: Cciradih
  links:
    - https://github.com/cciradih/
    - https://shang.qq.com/wpa/qunwpa?idkey=18ce00de201537ad6cb4eb43577815ef44a5b8a03c6f2c6ab7a9ddfa789e3848
    - mailto:mountain@cciradih.top
lang: zh-Hans
paginate: 5
paginate_path: "page:num"
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
