name: workflow
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: /checkout
      - run: pwd
      - run: ll
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/setup-node@v4
        with:
          path: /checkout
      - run: pwd
      - run: ll
      - run: npm install
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          path: /checkout
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - run: pwd
      - run: ll
